title            : Adventure Theme
author           :
  name           : Igor Padoim
  email          : igorpadoim@gmail.com
description      : A jekyll theme for Adventure-generated adventures.

markdown         : kramdown
plugins          :
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections      :
  adventures     :
    output       : true
    sort_by      : title

exclude          :
  - script/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - adventure-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - CODE-OF-CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - package.json
  - OGL.md
  - README.md
