title: Adventure Theme
footer_content: 'Copyright &copy; 2019 Igor Padoim. Distributed by an <a href="https://opensource.org/licenses/MIT">MIT license.</a>'

aux_links:
  'Adventure Theme on GitHub':
    - 'https://github.com/Nereare/adventure-theme'
  'Adventure Theme Gem':
    - 'https://rubygems.org/gems/adventure_theme'

remote_theme: pmarsceill/just-the-docs

plugins:
  - jemoji

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
